### ISSUE TITLE
more frequent change of image frames

### ISSUE THREAD

**Issue by dnabanita7** [dnabanita7/SimilarityIndex#7]
As of now, there is more frequent change of image frames as it changes for every other video/image frame. It would look better if it would change after 5/10 frames.

cc: @emmadickson

**Comment by emmadickson** [comment]
I think it might make sense to basically add something like the process_this_frame ternary operator in the image generator. ```process_this_frame = True if process_this_frame == False else False``` but instead of just a boolean doing a counter and resetting it if its at 5 or 6 or whatever.

**Comment by dnabanita7** [comment]
I guess right that would be the best way to handle this.
